#print("Hello world. Ignorance is a fucking bliss sometimes!!!!!!")
#print("Sometimes I feel depressed by politics")
print("How can I live happily ??")
#print("I hope I will have a bright future <3")
#print('The trip of a thousand miles starts with ONE step')